services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
        MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    volumes:
      - ./mysql:/var/lib/mysql
